"<da>"
	"da" Adv Sem/Time <W:0>
	"da" Adv Sem/Time <W:1>
"<lle>"
	"lle" Adv Sem/Time <W:0>
	"lle" Adv Sem/Time <W:1>
: 
"<go>"
	"go" Pcle Qst <W:0>
	"go" Pcle Qst <W:1>
:\n
"<dalle>"
	"dalle" Adv Sem/Time <W:0>
	"dalle" Adv Sem/Time <W:1>
: 
"<go>"
	"go" CS <W:0>
	"go" CS <W:1>
:\n
"<dalle>"
	"lle" Adv Sem/Time <W:0>
		"da" Adv Sem/Time <W:0>
	"lle" Adv Sem/Time <W:1>
		"da" Adv Sem/Time <W:1>
: 
"<go>"
	"go" Pcle Qst <W:0>
	"go" Pcle Qst <W:1>
"<,>"
	"," CLB <W:0>
:\n
