"<dalle go>"
	"go" Pcle Qst <W:0> "<go>"
		"lle" Adv Sem/Time <W:0> "<lle >"
			"da" Adv Sem/Time <W:0> "<da>"
	"go" Pcle Qst <W:1> "<go>"
		"lle" Adv Sem/Time <W:1> "<lle >"
			"da" Adv Sem/Time <W:1> "<da>"
:\n
"<dalle go>"
	"go" CS <W:0> "<go>"
		"dalle" Adv Sem/Time <W:0> "<dalle >"
	"go" CS <W:1> "<go>"
		"dalle" Adv Sem/Time <W:1> "<dalle >"
:\n
"<dalle go>"
	"go" Pcle Qst <W:0> "<go>"
		"lle" Adv Sem/Time <W:0> "<dalle >"
			"da" Adv Sem/Time <W:0>
	"go" Pcle Qst <W:1> "<go>"
		"lle" Adv Sem/Time <W:1> "<dalle >"
			"da" Adv Sem/Time <W:1>
"<,>"
	"," CLB <W:0>
:\n
