language: cpp

# Ubuntu 14.04 Trusty
sudo: required
dist: trusty

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

before_script:
    - ./autogen.sh

matrix:
    allow_failures:
        - os: linux
# Trusty doesn't have C++11, gcc nor clang :-/
